In [1]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# ==========================================================
# Task 1: Array Creation Shortcuts
# ==========================================================
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("\n1.1 arr1_1:")
print(arr1_1)

print("\n1.2 arr1_2:")
print(arr1_2)

print("\n1.3 arr1_3:")
print(arr1_3)

print("\n1.4 arr1_4:")
print(arr1_4)

# ==========================================================
# Task 2: Indexing and Slicing with Arrays
# ==========================================================
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed).
val2_1 = data[2, 3]

# 2.2 Extract the first row.
row2_2 = data[0]

# 2.3 Extract the last column.
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1.
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100.
filtered_elements2_5 = data[data > 100]

print("\n2.1 Element at row 2 column 3:")
print(val2_1)

print("\n2.2 First row:")
print(row2_2)

print("\n2.3 Last column:")
print(col2_3)

print("\n2.4 Sub-array:")
print(sub_arr2_4)

print("\n2.5 Elements greater than 100:")
print(filtered_elements2_5)

# ==========================================================
# Task 3: Conditional Operations
# ==========================================================
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))

# 3.1 Replace values less than 10 with 0.
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count even numbers.
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("\nOriginal Array:")
print(arr3_1)

print("\n3.1 Modified Array:")
print(arr3_2)

print("\n3.2 Number of Even Elements:")
print(even_count3_3)

# ==========================================================
# Task 4: Aggregation Functions
# ==========================================================
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

sum4_1 = np.sum(arr4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
max_rows4_3 = np.max(arr4_1, axis=1)
std4_4 = np.std(arr4_1)

print("\nArray:")
print(arr4_1)

print("\n4.1 Sum:")
print(sum4_1)

print("\n4.2 Mean of Columns:")
print(mean_cols4_2)

print("\n4.3 Maximum of Each Row:")
print(max_rows4_3)

print("\n4.4 Standard Deviation:")
print(std4_4)

# ==========================================================
# Task 5: Reshaping and Flattening
# ==========================================================
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

flattened_arr5_4 = reshaped_arr5_2.ravel()
flattened_arr5_5 = reshaped_arr5_2.flatten()

print("\nOriginal Array:")
print(arr5_1)

print("\n5.1 Reshaped (4x6):")
print(reshaped_arr5_2)

print("\n5.2 Reshaped (2x3x4):")
print(reshaped_arr5_3)

print("\n5.3 Flatten using ravel():")
print(flattened_arr5_4)

print("\nFlatten using flatten():")
print(flattened_arr5_5)

# ==========================================================
# Task 6: Broadcasting
# ==========================================================
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector

print("\nOriginal Array:")
print(arr6_1)

print("\n6.1 After Adding Scalar:")
print(result6_1)

print("\n6.2 After Adding Vector:")
print(result6_2)

# ==========================================================
# Task 7: Copying vs Viewing Arrays
# ==========================================================
print("\n--- Task 7: Copying vs Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7[:]
view_arr7[0] = 99

copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("\nOriginal Array after View Modification:")
print(original_arr7)

print("\nView Array:")
print(view_arr7)

print("\nCopy Array:")
print(copy_arr7)

# ==========================================================
# Task 8: Stacking and Splitting Arrays
# ==========================================================
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

part1, part2, part3 = np.vsplit(combined_arr8_3, [2, 4])

print("\n8.1 Vertical Stack:")
print(vstack_arr8_1)

print("\n8.2 Horizontal Stack:")
print(hstack_arr8_2)

print("\n8.3 Combined Array:")
print(combined_arr8_3)

print("\n8.4 Split Part 1:")
print(part1)

print("\nSplit Part 2:")
print(part2)

print("\nSplit Part 3:")
print(part3)

# ==========================================================
# Task 9: Sorting and Searching
# ==========================================================
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

sorted_arr9_1 = np.sort(arr9_1)
sorted_cols9_2 = np.sort(arr9_2d, axis=0)
idx9_3 = np.where(arr9_1 == 9)
max_idx9_4 = np.argmax(arr9_1)

print("\nOriginal 1D Array:")
print(arr9_1)

print("\n9.1 Sorted 1D Array:")
print(sorted_arr9_1)

print("\nOriginal 2D Array:")
print(arr9_2d)

print("\n9.2 Sorted Columns:")
print(sorted_cols9_2)

print("\n9.3 Index of value 9:")
print(idx9_3)

print("\n9.4 Index of Maximum Value:")
print(max_idx9_4)

print("\n========== Program Executed Successfully ==========")

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---

1.1 arr1_1:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

1.2 arr1_2:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1.3 arr1_3:
[[7 7 7 7]
 [7 7 7 7]]

1.4 arr1_4:
[[27 16 45 22 32]
 [28 50 33 34 43]
 [44 37 22 31 37]
 [41 45 32 46 39]
 [40 45 14 35 45]]

--- Task 2: Indexing and Slicing with Arrays ---

2.1 Element at row 2 column 3:
120

2.2 First row:
[10 20 30 40]

2.3 Last column:
[ 40  80 120 160]

2.4 Sub-array:
[[ 50  60]
 [ 90 100]]

2.5 Elements greater than 100:
[110 120 130 140 150 160]

--- Task 3: Conditional Operations ---

Original Array:
[[17 10 13 19  